[package]
name = "dangling-pointer-rampage"
version = "0.1.0"
authors = ["Artur Augusto Martins <arturaugusto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
